mail-settings:
  sender: i3458671395@yeah.net
  password: RLDMTOKVJPOIBXMF
  server: smtp.yeah.net
  port: 465
request-settings:
  key: cd8137e734c84cf4a3add2bce772e446
  location: 101210612
  mode: dev
  unit: m
  lang: zh
other-settings:
  receiver:
  - i3458671395@yeah.net
  icon-style: set-1-bw
  weather-picture: false
  send-times:
  - '08:00'
  - '12:00'
  - '18:00'
only-view-settings:
  city-name: 黄岩-浙江省-台州
  time: Sat Oct 09 21:06:09 2021
  user: Tapso
